import React from 'react';
import {CATEGORIES,pareto,simulate} from './analytics.mjs';
import type {Category,Evaluated,Parameters,Scored,Simulation} from './types';
const numberFormat=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:1});
const cashFormat=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
export const num=(x:number|null|undefined)=>x===null||x===undefined?'N/D':numberFormat.format(x);
export const brl=(x:number|null|undefined)=>x===null||x===undefined?'N/D':cashFormat.format(x);
export const compact=(x:number)=>Math.abs(x)>=1e6?num(x/1e6)+' mi':Math.abs(x)>=1000?num(x/1000)+' mil':num(x);
export const percent=(x:number|null|undefined)=>x===null||x===undefined?'N/D':num(x*100)+'%';
export const titleFor=(t:Scored)=>t.neighborhood||'Setor '+t.id.slice(-4);
export const colorFor=(score:number)=>score>=75?'#58d7af':score>=60?'#75b9ed':score>=40?'#d3bb79':'#6f879c';
export const componentColors=['#5faaff','#70d5c0','#ba9af4','#efc877'];
export function ContributionBars({row}:{row:Scored}){return <div className="contributions" aria-label="Decomposição do índice de oportunidade">{row.components.map((c,i)=><div className="contribution" key={c.label}><div><span>{c.label}</span><b>{c.contribution===null?'N/D':num(c.contribution)} <small>/ {num(c.weight*100)}</small></b></div><div className="track"><i style={{width:String(c.contribution===null?0:c.contribution/Math.max(.001,c.weight*100)*100)+'%',background:componentColors[i]}}/></div><small>{c.value===null?'Insumo não disponível para toda a geometria':`Indicador normalizado: ${num(c.value)} · peso ${percent(c.weight)}`}</small></div>)}</div>;}
export function MixChart({row}:{row:Scored}){const max=Math.max(1,...Object.values(row.counts));return <div className="mixchart">{(Object.keys(CATEGORIES) as Category[]).map(k=><div key={k}><span><i style={{background:CATEGORIES[k].color}}/>{CATEGORIES[k].label}</span><div className="track"><i style={{width:String(row.counts[k]/max*100)+'%',background:CATEGORIES[k].color}}/></div><b>{row.counts[k]}</b></div>)}<p className="fine">{row.n} objetos associados ao setor; não são contratos ou empresas únicas.</p></div>;}
export function Scatter({rows,selected,onSelect}:{rows:Evaluated[];selected:string|null;onSelect:(id:string)=>void}){
 const good=rows.filter(t=>t.result&&t.density!==null),w=620,h=295,left=65,right=20,top=20,bottom=52;
 const maxX=Math.max(30,...good.map(t=>t.density??0)),minY=Math.min(0,...good.map(t=>t.result!.npv)),maxY=Math.max(10000,...good.map(t=>t.result!.npv));
 const px=(x:number)=>left+Math.log1p(x)/Math.log1p(maxX)*(w-left-right),py=(y:number)=>top+(maxY-y)/Math.max(1,maxY-minY)*(h-top-bottom);
 const ticks=[0,1,5,10,30,100].filter(x=>x<=maxX);
 return <div className="chart"><svg viewBox={`0 0 ${w} ${h}`} role="group" aria-label="Densidade residencial versus VPL incremental. Selecione um setor."><title>Densidade de domicílios ocupados versus VPL de 120 meses</title>{[0,.25,.5,.75,1].map(a=>{const value=minY+(maxY-minY)*a;return <g key={a}><line className="gridline" x1={left} x2={w-right} y1={py(value)} y2={py(value)}/><text x={left-8} y={py(value)+4} textAnchor="end">{compact(value)}</text></g>;})}<line className="zeroline" x1={left} x2={w-right} y1={py(0)} y2={py(0)}/>{ticks.map(x=><g key={x}><line className="gridline" x1={px(x)} x2={px(x)} y1={top} y2={h-bottom}/><text x={px(x)} y={h-bottom+19} textAnchor="middle">{x}</text></g>)}{good.map(t=><circle key={t.id} data-sector-point={t.id} cx={px(t.density??0)} cy={py(t.result!.npv)} r={selected===t.id?7:3.5} fill={colorFor(t.score)} opacity={selected===t.id?1:.66} stroke={selected===t.id?'#fff':'none'} strokeWidth={2} role="button" tabIndex={0} aria-label={`${titleFor(t)}, setor ${t.id}, ${num(t.density)} domicílios por hectare, VPL ${brl(t.result!.npv)}`} onClick={()=>onSelect(t.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(t.id);}}}><title>{titleFor(t)} · {t.id}\nDPO/ha: {num(t.density)} · VPL: {brl(t.result!.npv)}\nIOT: {num(t.score)}</title></circle>)}<text x={left} y={12}>VPL incremental · R$</text><text x={(left+w-right)/2} y={h-8} textAnchor="middle">DPO / hectare · eixo log(1 + densidade)</text></svg><p className="fine">Cor = prioridade de triagem. Acima da linha zero = VPL positivo sob as premissas selecionadas; não é autorização de investimento.</p></div>;
}
export function Pareto({rows,topN}:{rows:Scored[];topN:number}){const data=pareto(rows),w=530,h=250,l=48,r=20,t=18,b=38;const x=(n:number)=>l+n*(w-l-r),y=(n:number)=>h-b-n*(h-b-t),path='M'+x(0)+','+y(0)+' '+data.map(d=>`L${x(d.x)},${y(d.y)}`).join(' '),mark=data[Math.min(topN,data.length)-1];return <div className="chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Participação acumulada dos domicílios pela ordem de prioridade"><title>Concentração da base residencial no ranking territorial</title>{[0,.25,.5,.75,1].map(v=><g key={v}><line className="gridline" x1={l} x2={w-r} y1={y(v)} y2={y(v)}/><text x={l-8} y={y(v)+4} textAnchor="end">{v*100}%</text><text x={x(v)} y={h-17} textAnchor="middle">{v*100}%</text></g>)}<path d={path} fill="none" stroke="#70d5c0" strokeWidth={3}/>{mark&&<g><line className="zeroline" x1={x(mark.x)} x2={x(mark.x)} y1={t} y2={h-b}/><circle cx={x(mark.x)} cy={y(mark.y)} r={5} fill="#f2cf83"/><text x={Math.min(w-r-30,x(mark.x)+8)} y={Math.max(17,y(mark.y)-10)}>{percent(mark.y)}</text></g>}</svg><p className="fine">Eixo X: setores acumulados no ranking. Eixo Y: domicílios ocupados em 2022. Não supõe captação igual à base censitária.</p></div>;}
export function CashChart({base,stress}:{base:Simulation;stress:Simulation}){const w=680,h=260,l=65,r=18,t=20,b=40,all=[...base.series,...stress.series],min=Math.min(0,...all.map(x=>x.cumulative)),max=Math.max(1,...all.map(x=>x.cumulative));const px=(n:number)=>l+n/120*(w-l-r),py=(v:number)=>t+(max-v)/(max-min)*(h-t-b),path=(s:Simulation)=>s.series.map((v,i)=>`${i?'L':'M'}${px(v.month)},${py(v.cumulative)}`).join(' ');return <div className="chart"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label="Fluxo de caixa acumulado por mês para base e estresse"><title>Capital incremental acumulado em 120 meses</title>{[0,.25,.5,.75,1].map(a=>{const v=min+(max-min)*a;return <g key={a}><line className="gridline" x1={l} x2={w-r} y1={py(v)} y2={py(v)}/><text x={l-9} y={py(v)+4} textAnchor="end">{compact(v)}</text></g>;})}<line className="zeroline" x1={l} x2={w-r} y1={py(0)} y2={py(0)}/>{[0,24,48,72,96,120].map(m=><text key={m} x={px(m)} y={h-16} textAnchor="middle">M{m}</text>)}<path d={path(base)} fill="none" stroke="#70d5c0" strokeWidth={3}/><path d={path(stress)} fill="none" stroke="#e39a7a" strokeWidth={2} strokeDasharray="6 4"/></svg><div className="inline-legend"><span><i style={{background:'#70d5c0'}}/>Premissas atuais</span><span><i style={{background:'#e39a7a'}}/>Estresse combinado</span></div></div>;}
export function Sensitivity({row,parameters,onApply}:{row:Scored;parameters:Parameters;onApply:(price:number,takeup:number)=>void}){const prices=[99,119,139,159,179],takeups=[.15,.25,.35,.45,.55];return <div className="sensitivity"><table><caption>VPL incremental por preço e penetração · R$ mil · clique para aplicar</caption><thead><tr><th>ARPU ↓ / adesão →</th>{takeups.map(t=><th key={t}>{percent(t)}</th>)}</tr></thead><tbody>{prices.map(price=><tr key={price}><th>R$ {price}</th>{takeups.map(t=>{const s=simulate(row,{...parameters,arpu:price,penetration:t})!;return <td key={t}><button className={s.npv>=0?'cell-positive':'cell-negative'} data-price={price} data-takeup={t} aria-label={`Aplicar ARPU ${price} e penetração ${t*100} por cento, VPL ${brl(s.npv)}`} onClick={()=>onApply(price,t)}>{num(s.npv/1000)}</button></td>;})}</tr>)}</tbody></table><p className="fine">Todas as demais premissas ficam constantes. A tabela não mede elasticidade da demanda nem probabilidade de sucesso.</p></div>;}
