import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import type {Feature,FeatureCollection,Point} from 'geojson';
import type {Map as MapInstance,GeoJSONSource,MapMouseEvent} from 'maplibre-gl';
import {Map,useMap} from './vendor/map';
import './map.css';

type Category='educacao'|'saude'|'servicos'|'consumo'|'comunidade';
type Properties={id:string;name:string;category:Category;amenity:string;city:'sinop'|'sorriso';position:string};
type Place=Feature<Point,Properties>;
type GeoData={schema:number;capturedAt:string;baseTimestamp:string;source:string;sourceUrl:string;license:string;method:string;rawCount:number;collection:FeatureCollection<Point,Properties>;bounds:Record<string,number[]>};
type Summary={npv:number;peakFunding:number;irr?:number[];payback?:number|null};
declare global{interface Window{AB_GEO:GeoData;PRECOMPUTED?:Record<string,{summary:Summary}>;EVTEO?:{SCENARIOS:Record<string,{name:string}>};__AB_MAP_READY?:boolean}}
const data=window.AB_GEO;
if(!data||data.schema!==1||!Array.isArray(data.collection?.features))throw new Error('MAP_DATA_INVALID');
const categories:Record<Category,{label:string;color:string;thesis:string;gate:string}>={
 educacao:{label:'Educação',color:'#56b8f8',thesis:'Conectividade de campus, Wi-Fi gerenciado e continuidade para rotinas acadêmicas.',gate:'Validar decisor, orçamento, calendário de contratação e infraestrutura interna.'},
 saude:{label:'Saúde',color:'#75d5b0',thesis:'Continuidade para clínicas, atendimento digital e sistemas assistenciais.',gate:'Qualificar criticidade, proteção de dados, redundância física e SLA executável.'},
 servicos:{label:'Serviços',color:'#a99aff',thesis:'Conexão empresarial para pagamentos, sistemas de gestão e operação distribuída.',gate:'Confirmar endereço operacional, contrato vigente, CIR e custo de ativação.'},
 consumo:{label:'Comércio e alimentação',color:'#f7bf66',thesis:'Wi-Fi para clientes, operação de caixa e conectividade de pequenas empresas.',gate:'Medir disposição a pagar, concorrência por endereço e margem após suporte.'},
 comunidade:{label:'Equipamentos e comunidade',color:'#f28fac',thesis:'Equipamentos públicos, espaços de eventos e polos de circulação.',gate:'Verificar regras de contratação e elegibilidade antes de contabilizar receita.'},
};
const center:Record<string,[number,number]>={sinop:[-55.508,-11.859],sorriso:[-55.727,-12.545],regiao:[-55.62,-12.19]};
const fmt=new Intl.NumberFormat('pt-BR');
const money=(x:number)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:2}).format(x/1e6)+' mi';
const normalize=(x:string)=>x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
function download(name:string,body:string,type='application/json'){const url=URL.createObjectURL(new Blob([body],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function readScenarios(){try{return window.parent===window?null:window.parent.PRECOMPUTED??null;}catch{return null;}}
function Layer({points,heat,dots,radius,selected,onSelect,onReady,onStatus,onVisible}:{points:Place[];heat:boolean;dots:boolean;radius:number;selected:string|null;onSelect:(p:Place)=>void;onReady:(map:MapInstance)=>void;onStatus:(status:string)=>void;onVisible:(n:number)=>void}){
 const {map,isLoaded}=useMap();
 useEffect(()=>{if(!map||!isLoaded)return;onReady(map);window.__AB_MAP_READY=true;onStatus('Mapa pronto');const count=()=>onVisible(points.filter(f=>map.getBounds().contains(f.geometry.coordinates as [number,number])).length);count();map.on('moveend',count);return()=>{map.off('moveend',count);};},[map,isLoaded,points,onReady,onStatus,onVisible]);
 useEffect(()=>{if(!map)return;const fail=()=>onStatus('Base cartográfica indisponível; catálogo preservado');map.on('error',fail);return()=>{map.off('error',fail);};},[map,onStatus]);
 useEffect(()=>{
  if(!map||!isLoaded)return;
  const collection:FeatureCollection<Point,Properties>={type:'FeatureCollection',features:points};
  if(!map.getSource('ab-pois'))map.addSource('ab-pois',{type:'geojson',data:collection});else (map.getSource('ab-pois') as GeoJSONSource).setData(collection);
  if(!map.getLayer('ab-heat'))map.addLayer({id:'ab-heat',source:'ab-pois',type:'heatmap',paint:{'heatmap-weight':1,'heatmap-intensity':1.3,'heatmap-radius':radius,'heatmap-opacity':0.76,'heatmap-color':['interpolate',['linear'],['heatmap-density'],0,'rgba(32,97,170,0)',0.15,'#285d9a',0.35,'#4b99c1',0.55,'#67c6ae',0.75,'#dfd174',1,'#ffa765']}});
  if(!map.getLayer('ab-points'))map.addLayer({id:'ab-points',source:'ab-pois',type:'circle',paint:{'circle-radius':['interpolate',['linear'],['zoom'],9,2,14,5,17,7],'circle-color':['match',['get','category'],...Object.entries(categories).flatMap(([k,v])=>[k,v.color]),'#ffffff'],'circle-stroke-color':'#0e1926','circle-stroke-width':1.5,'circle-opacity':0.92}});
  map.setLayoutProperty('ab-heat','visibility',heat?'visible':'none');map.setPaintProperty('ab-heat','heatmap-radius',radius);map.setLayoutProperty('ab-points','visibility',dots?'visible':'none');
  map.setPaintProperty('ab-points','circle-stroke-color',['case',['==',['get','id'],selected??''],'#ffffff','#0e1926']);
  map.setPaintProperty('ab-points','circle-stroke-width',['case',['==',['get','id'],selected??''],3,1.2]);
 },[map,isLoaded,points,heat,dots,radius,selected]);
 useEffect(()=>{if(!map||!isLoaded)return;const click=(e:MapMouseEvent)=>{const feature=map.queryRenderedFeatures(e.point,{layers:['ab-points']})[0];const place=points.find(p=>p.properties.id===feature?.properties?.id);if(place)onSelect(place);};const enter=()=>{map.getCanvas().style.cursor='pointer';},leave=()=>{map.getCanvas().style.cursor='';};map.on('click','ab-points',click);map.on('mouseenter','ab-points',enter);map.on('mouseleave','ab-points',leave);return()=>{map.off('click','ab-points',click);map.off('mouseenter','ab-points',enter);map.off('mouseleave','ab-points',leave);};},[map,isLoaded,points,onSelect]);
 return null;
}
class MapBoundary extends React.Component<{children:React.ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return{failed:true};}render(){return this.state.failed?<div className="map-fallback"><h2>O mapa não pôde ser renderizado.</h2><p>O catálogo, os filtros e as métricas continuam disponíveis. Reative WebGL ou atualize o navegador.</p></div>:this.props.children;}}
function App(){
 const [city,setCity]=useState('sinop'),[query,setQuery]=useState(''),[active,setActive]=useState<Category[]>(Object.keys(categories) as Category[]),[heat,setHeat]=useState(true),[dots,setDots]=useState(true),[radius,setRadius]=useState(48),[selected,setSelected]=useState<Place|null>(null),[visible,setVisible]=useState(0),[status,setStatus]=useState('Carregando base cartográfica…'),[limit,setLimit]=useState(25),[scenario,setScenario]=useState('ancorado'),[method,setMethod]=useState(false);
 const mapRef=useRef<MapInstance|null>(null),viewportRef=useRef<HTMLDivElement|null>(null);
 const points=useMemo(()=>data.collection.features.filter(f=>(city==='regiao'||f.properties.city===city)&&active.includes(f.properties.category)&&normalize(f.properties.name).includes(normalize(query))),[city,active,query]);
 const counts=useMemo(()=>Object.fromEntries(Object.keys(categories).map(c=>[c,points.filter(f=>f.properties.category===c).length])),[points]);
 const topCategory=(Object.keys(categories) as Category[]).sort((a,b)=>counts[b]-counts[a])[0];
 const scenarios=useMemo(readScenarios,[]),summary=scenarios?.[scenario]?.summary;
 const select=useCallback((place:Place)=>{setSelected(place);mapRef.current?.flyTo({center:place.geometry.coordinates as [number,number],zoom:15,duration:reduced?0:650});},[]);
 const ready=useCallback((map:MapInstance)=>{mapRef.current=map;},[]);
 useEffect(()=>{const timer=setTimeout(()=>setStatus(s=>s==='Mapa pronto'?s:'Base demorando a responder; catálogo disponível'),16000);return()=>clearTimeout(timer);},[]);
 useEffect(()=>{mapRef.current?.flyTo({center:center[city],zoom:city==='regiao'?8.4:12.2,pitch:0,duration:reduced?0:750});setSelected(null);setLimit(25);},[city]);
 useEffect(()=>{setLimit(25);if(selected&&!points.some(p=>p.properties.id===selected.properties.id))setSelected(null);},[points,selected]);
 const toggle=(c:Category)=>setActive(a=>a.includes(c)?a.filter(x=>x!==c):[...a,c]);
 const reset=()=>{setCity('sinop');setQuery('');setActive(Object.keys(categories) as Category[]);setHeat(true);setDots(true);setRadius(48);mapRef.current?.flyTo({center:center.sinop,zoom:12.2,pitch:0,duration:reduced?0:600});};
 return <div className="workspace">
  <header className="head"><div><div className="eyebrow">AB / INTELIGÊNCIA GEOGRÁFICA</div><h1>O território revela<br/><span>onde investigar primeiro.</span></h1><p>Da concentração de atividades ao próximo bloco de expansão.</p></div><div className="head-actions"><button onClick={()=>setMethod(!method)}>Metodologia ↗</button><button className="accent" onClick={()=>download('AB_recorte_cartografico.geojson',JSON.stringify({type:'FeatureCollection',metadata:{source:data.source,date:data.baseTimestamp,scope:'Registros cartográficos; não clientes ou demanda'},features:points},null,2))}>Exportar recorte ↓</button></div></header>
  <div className="evidence-strip"><span className="signal"/>BASE CARTOGRÁFICA REAL <b>≠</b> DEMANDA COMPROVADA<span className="stamp">OSM · {new Date(data.baseTimestamp).toLocaleDateString('pt-BR',{timeZone:'UTC'})}</span></div>
  {method&&<section className="method"><h2>Como ler este mapa</h2><p>{data.method} As janelas não representam todo o território municipal. O mapa de calor usa peso 1 por registro e suavização visual em pixels; não mede domicílios por hectare. Uma instituição pode conter vários objetos cartográficos.</p><p>Os grupos comerciais são hipóteses de abordagem. Não há cobertura concorrente, demanda reprimida, renda por bairro, saturação de postes ou probabilidade de retorno medidas nesta camada. Os indicadores financeiros abaixo pertencem ao cenário completo do EVTEO, não aos pontos do mapa.</p><p>A base visual usa CARTO/OSM. O navegador consulta imagens e vetores de localização; senhas e os dados privados do estudo não são enviados ao fornecedor da base.</p></section>}
  <section className="metrics" aria-label="Métricas do recorte"><article><small>REGISTROS NO RECORTE</small><strong>{fmt.format(points.length)}</strong><span>objetos cartográficos filtrados</span></article><article><small>NA ÁREA VISÍVEL</small><strong>{fmt.format(visible)}</strong><span>mova o mapa para explorar</span></article><article><small>GRUPO MAIS MAPEADO</small><strong className="word">{points.length?categories[topCategory].label:'Sem registros'}</strong><span>{points.length?counts[topCategory]:0} registros · não é market share</span></article><article><small>VERIFICAÇÃO DE CAMPO</small><strong className="word warning">Pendente</strong><span>não autoriza obra ou receita</span></article></section>
  <section className="map-workspace">
   <aside className="layers"><div className="panel-title">EXPLORAR O TERRITÓRIO <span>01</span></div><label htmlFor="city">Janela urbana</label><select id="city" value={city} onChange={e=>setCity(e.target.value)}><option value="sinop">Sinop</option><option value="sorriso">Sorriso</option><option value="regiao">Comparar as duas cidades</option></select><label htmlFor="search">Buscar no catálogo</label><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nome do local…"/><div className="divider"/><div className="panel-title">CAMADAS DE ATIVIDADE</div>{Object.entries(categories).map(([key,v])=><label className="check" key={key}><input type="checkbox" checked={active.includes(key as Category)} onChange={()=>toggle(key as Category)}/><i style={{background:v.color}}/>{v.label}<span>{counts[key]}</span></label>)}<div className="divider"/><label className="check"><input type="checkbox" checked={heat} onChange={e=>setHeat(e.target.checked)}/>Mapa de calor</label><label className="check"><input type="checkbox" checked={dots} onChange={e=>setDots(e.target.checked)}/>Pontos interativos</label><label htmlFor="radius">Suavização visual <b>{radius}px</b></label><input id="radius" type="range" min="15" max="100" step="1" value={radius} onChange={e=>setRadius(Number(e.target.value))}/><button className="reset" onClick={reset}>Restaurar recorte</button><p className="fine">Mais cor indica concentração de registros mapeados, não mais clientes disponíveis.</p></aside>
   <div className="map-frame" ref={viewportRef}><div className="map-status" role="status"><span className={status==='Mapa pronto'?'signal':''}/>{status}</div><MapBoundary><Map theme="dark" center={center.sinop} zoom={12.2} minZoom={7} maxZoom={18} className="ab-map" attributionControl={{compact:true}}><Layer points={points} heat={heat} dots={dots} radius={radius} selected={selected?.properties.id??null} onSelect={select} onReady={ready} onStatus={setStatus} onVisible={setVisible}/></Map></MapBoundary><div className="map-tools"><button aria-label="Aproximar mapa" onClick={()=>mapRef.current?.zoomIn()}>+</button><button aria-label="Afastar mapa" onClick={()=>mapRef.current?.zoomOut()}>−</button><button aria-label="Alternar perspectiva" onClick={()=>mapRef.current?.easeTo({pitch:mapRef.current.getPitch()>0?0:45,duration:reduced?0:450})}>3D</button><button aria-label="Mapa em tela cheia" onClick={()=>{if(document.fullscreenElement)void document.exitFullscreen();else void viewportRef.current?.requestFullscreen();}}>⛶</button></div><div className="legend"><b>CONCENTRAÇÃO CARTOGRÁFICA</b><div className="gradient"/><div><span>Dispersa</span><span>Concentrada</span></div><small>Escala relativa ao zoom · peso unitário</small></div></div>
   <aside className="inspector"><div className="panel-title">INSPECIONAR E QUALIFICAR <span>02</span></div>{selected?<><div className="tag" style={{color:categories[selected.properties.category].color}}>{categories[selected.properties.category].label}</div><h2>{selected.properties.name}</h2><p className="location">{selected.properties.city==='sinop'?'Sinop':'Sorriso'} · {selected.geometry.coordinates.map(x=>x.toFixed(5)).join(', ')}</p><div className="divider"/><small className="eyebrow">TESE DE ABORDAGEM · PROPOSTA</small><p>{categories[selected.properties.category].thesis}</p><small className="eyebrow">PRÓXIMA EVIDÊNCIA NECESSÁRIA</small><p>{categories[selected.properties.category].gate}</p><div className="callout">Um registro no mapa é uma pista de prospecção — não comprova demanda, contrato ou endereço tecnicamente atendível.</div><a className="source-link" href={'https://www.openstreetmap.org/'+selected.properties.id} target="_blank" rel="noopener noreferrer">Consultar objeto na fonte ↗</a><p className="fine">Localização: {selected.properties.position}. Base colaborativa sujeita a duplicidades e desatualização.</p></>:<><h2>Cada ponto abre<br/>uma investigação.</h2><p>Selecione um registro no mapa ou na lista para conectar o contexto geográfico à qualificação comercial.</p><div className="mini-flow"><span>Local mapeado</span><i>↓</i><span>Decisor e necessidade</span><i>↓</i><span>Viabilidade física</span><i>↓</i><span>Receita contratável</span></div><p className="fine">A comparação entre cidades não deve usar a quantidade de objetos do OSM como estimativa do mercado total.</p></>}</aside>
  </section>
  <section className="bottom-grid"><article className="catalog"><div className="panel-title">CATÁLOGO DO RECORTE <span>{points.length} registros</span></div><div className="table-wrap"><table><thead><tr><th>Local mapeado</th><th>Grupo</th><th>Janela</th><th/></tr></thead><tbody>{points.slice(0,limit).map(p=><tr key={p.properties.id} className={p.properties.id===selected?.properties.id?'selected':''}><td>{p.properties.name}</td><td>{categories[p.properties.category].label}</td><td>{p.properties.city}</td><td><button onClick={()=>select(p)} aria-label={'Inspecionar '+p.properties.name}>↗</button></td></tr>)}</tbody></table>{!points.length&&<p className="empty">Nenhum registro corresponde a este filtro. Altere o grupo, a busca ou a cidade.</p>}</div>{points.length>limit&&<button className="more" onClick={()=>setLimit(n=>n+25)}>Carregar mais registros</button>}</article><article className="execution"><div className="panel-title">DO MAPA AO BLOCO DE REDE <span>03</span></div><h2>Ganhar escala começa<br/>por provar a microárea.</h2>{['Validar os endereços e entrevistar os decisores','Levantar rede, postes, travessias e rotas reais','Cotação vinculante + pré-venda documentada','Recalcular VPL, caixa e capacidade de operação'].map((v,i)=><div className="step" key={v}><b>{String(i+1).padStart(2,'0')}</b><span>{v}</span></div>)}<p className="fine">Sequência proposta de execução. Nenhuma etapa foi marcada como concluída por esta visualização.</p></article></section>
  <section className="finance"><div><div className="eyebrow">CONTEXTO FINANCEIRO DO ESTUDO</div><h2>Território + disciplina de capital.</h2><p>O mapa orienta investigação. O fluxo de caixa decide o investimento.</p></div><label>Cenário do EVTEO<select value={scenario} onChange={e=>setScenario(e.target.value)}><option value="misto">Misto disciplinado</option><option value="ancorado">B2B ancorado — hipótese</option><option value="residencial">Residencial pressionado</option><option value="adverso">Estresse + falha comum</option></select></label><div className="financial-stats"><div><small>VPL DO PROJETO</small><strong>{summary?money(summary.npv):'No painel executivo'}</strong></div><div><small>EXPOSIÇÃO MÁXIMA DE CAIXA</small><strong>{summary?money(summary.peakFunding):'No painel executivo'}</strong></div></div><p className="fine">Hipóteses do modelo original · horizonte de 120 meses · taxa de 18% a.a. · sem valor terminal. Não há VPL observado por ponto ou por bairro.</p></section>
  <footer className="map-footer"><span>{data.license} · Recorte editorial · {data.rawCount} objetos brutos / {data.collection.features.length} elegíveis</span><a href="https://www.alexandrebelo.com.br/" target="_blank" rel="noopener noreferrer">por <b>AB</b> | www.alexandrebelo.com.br</a></footer>
 </div>;
}
createRoot(document.getElementById('map-root')!).render(<App/>);
